# entry
name: example
on:
  workflow_dispatch:
    inputs:
      script_url:
        description: 'remote script url (ps1)'
        required: true
      type:
        description: 'your host type'
        required: true

jobs:
  runner:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: collie
        if: ${{ inputs.script_url != '' && inputs.type != '' }}
        uses: ./
        with:
          script_url: ${{ inputs.script_url }}
          host_type: "windows"
